(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.grafik_full_120px = function() {
	this.initialize(img.grafik_full_120px);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,600);


(lib.grafik_step1_120px = function() {
	this.initialize(img.grafik_step1_120px);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,600);


(lib.grafik_step2_120px = function() {
	this.initialize(img.grafik_step2_120px);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,600);


(lib.grafik_step3_120px = function() {
	this.initialize(img.grafik_step3_120px);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,600);


(lib.huawei_P20_Pro_Charlotte_Black_FrontRight_BN_eciRGBv2 = function() {
	this.initialize(img.huawei_P20_Pro_Charlotte_Black_FrontRight_BN_eciRGBv2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,48,124);


(lib.lg_44px = function() {
	this.initialize(img.lg_44px);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,45,97);


(lib.s9plus_100px = function() {
	this.initialize(img.s9plus_100px);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,100,212);


(lib.samsung_galaxy_s9plus_g360_Coral_Blue_l30 = function() {
	this.initialize(img.samsung_galaxy_s9plus_g360_Coral_Blue_l30);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,37,100);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib._1und1_logo_80px = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Logo_Neu
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgytsImdAAIAAmdIOfAAMAAAAoTIoCAAg");
	this.shape.setTransform(61.9,38.7,0.141,0.141);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgytsImdAAIAAmdIOfAAMAAAAoTIoCAAg");
	this.shape_1.setTransform(15.3,38.7,0.141,0.141);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AijUyQmOgCjzjAQj5jEgZldQgPjWCJjNQCLjPENibQiujfg2hxQg1hwAAiMQAAjvC4icQC6icEgAAQEKAACsCfQCrCfAAD1QAAC1hXCTQhZCZjfC5IG+JcQAcgZAUiAQAUiAgFh9IgKiNIGfAAQAAA3AFBkQAAD6gtCjQgvCrhzCTIFJG1In+AAIhzibQiNByiLAuQiJAtjBAAIgIAAgApgJCQAFCeB6BfQB5BeDFAAQBwAABdgnQBNggBNhAInoqLQlDDWAHDhgAlHuIQg7A2AABUQAABQAiBDQAiBBBwCRQCAhcA7hdQA2hVAAhbQAAhWg4gzQg4gzhhAAQhdAAg8A2g");
	this.shape_2.setTransform(41.5,38.8,0.141,0.141);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#134094").s().p("Egq0Aq1MAAAhVpMBVpAAAMAAABVpg");
	this.shape_3.setTransform(40,40,0.141,0.141);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AmPGQIAAsfIMfAAIAAMfg");
	this.shape_4.setTransform(40,40);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib._1und1_logo_80px, new cjs.Rectangle(0,0,80,80), null);


(lib.mc_whitespot_02 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// WhiteSpot
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgKuA15QiygXgXgeQhKhwgEmzIAAgCQgCiAAIlLQAIl+ANlAQAPlmADhrQAEicgFiXQgPnuhfi/QgfhABalDQBZk9CgmSQCvm3C6laQDWmLCyiwQAWgXAADbQAACDgKFtQgKFoAACIQABDZAWgUQAngmDQr6QDOrzAqgZQEti5C9tXUgBYAP2gBpAlXQg2TQgOEaQgiKmgZCZQgoD5hjEnQhwFRh4CsQgtBCjCAlQinAejtABQjZAAivgUg");
	this.shape.setTransform(65.5,55.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_whitespot_02, new cjs.Rectangle(-38.5,-291.1,208,693.9), null);


(lib._1und1_rahmen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 1u1_rahmen
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,2,1).dr(-60,-300,120,600);
	this.shape.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib._1und1_rahmen, new cjs.Rectangle(-1,-1,122,602), null);


(lib._1und1_hintergrund = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// fond_verlauf_gesamt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0E3274").s().p("EgJXAu4MAAAhdvISvAAMAAABdvg");
	this.shape.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib._1und1_hintergrund, new cjs.Rectangle(0,0,203,4566), null);


(lib.mc_stoerer = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// typo
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#134094").s().p("AhWB/IgLgDIABgRQAMAGAJAAQAGAAAEgCQADgCACgDQACgFAAgOIAAAAQgBAEgEAEIgFADQgEABgEAAQgFAAgEgBQgEgCgDgEQgEgEgCgHQgBgEgBgMQAAgIACgGQABgHADgEQAEgFAEgCQAEgCAGAAIAIABIAFADQADADACAEIABAAIAAgKIAUAAIgBAPIAAAsQAAAOgEAIIgEAGIgGAFIgJADQgFABgGAAIgOgBgAhKAvIgDAGIgBAMQAAAUAJAAQADAAADgCIADgEQACgFAAgJQAAgHgCgGIgDgFQgDgCgCAAQgEAAgCACgADrBjIgHgEIgEgHQgCgEAAgEQAAgXAiAAIAGAAQAAgNgNAAIgIABIgKAFIgBgPIAKgDIALgBQAJAAAGABQAGACADADQADADABAFQACAEAAAGIAAAZIAAATIgSAAIgBgJQgBADgFAEIgGACIgHABQgFAAgDgBgAD4BEQgDACgCACQgCACAAAEQAAAJAJAAQAMAAAAgRIAAgDQgJAAgFABgACiBiQgEgDgDgFQgDgFgCgGQgBgHAAgIQAAgHABgGQABgGADgFQADgEAFgDQAEgCAHAAIAGAAIAFADQAEADACAFIAAAAIAAgoIAVAAIAABSIAAAPIgTAAIgBgLIAAAAQgCAFgEADIgFADQgDABgEAAQgGAAgFgCgACvAuQgCACgBADIgCAHIAAAHIABANIADAFQADACADAAQADAAACgCIADgFQACgFAAgIIAAgHIgCgHIgDgFQgCgBgDAAQgDAAgCABgAAABkIgGgCIgGgDIgFgFQgEgEgCgHQgCgGAAgIQAAgHACgGQACgGADgFQAEgFAGgDIAGgCIAGAAQAdAAAAAjIAAAFIgnAAIABAGIADAFIAEADQAEABAEAAIAKgBIAJgEIABAPIgLADIgLABgAAOA8QAAgIgCgEIgDgEQgCgBgDAAQgKAAAAARIAUAAIAAAAgAjIBkIgHgCQgGgDgEgFQgEgEgCgHQgCgGAAgIQAAgHACgHQACgGAEgFQAEgEAGgDIAHgCIAHAAQAFAAAJACQAGADAEAEQAEAFACAGQACAHAAAHQAAAIgCAGQgCAHgEAEQgEAFgGADQgJACgFAAgAjGAuIgDAEIgCAGIAAASIACAHIADAEQACABADAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAIADgEIACgHIABgJIgBgJIgCgGIgDgEIgFgBIgFABgAEvBjIAAgTIATAAIAAATgABSBjIAAgpQAAgGgCgDQgCgCgEAAQgEAAgDAEQgCADAAAHIAAAmIgUAAIAAg1IgBgOIATAAIABALQACgGAFgDIAFgDIAHAAQAFAAAEABQAEACADAEIADAHIABAKIAAAsgAiVBjIAAg1IAAgOIATAAIAAAMIAHgKIAFgCIAHgBIADAAIAAASIgHAAQgEAAgDABIgEAFIgCAHIAAAlgAkCBjIAAgpQAAgGgCgDQgCgCgDAAQgFAAgCADQgCACAAAEIAAArIgUAAIAAgpQAAgGgDgDQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgFABIgDADQgCADAAAHIAAAmIgUAAIAAg1IgBgOIATAAIABALQACgGAFgDIAFgDIAHAAIAGAAIAFADQAEACADAGQACgGAEgCIAFgDIAHAAQAGAAAEABQADACADAEIADAHIABAKIAAAsgAExBGIgDg9IAVAAIgDA9gAGJgPIAGgiIATAAIgKAigAFugeQgEgBgCgCQgDgDgCgDQgBgEAAgGIAAgiIgLAAIAAgOIALAAIAAgOIAUgHIAAAVIAOAAIAAAOIgOAAIAAAfQAAAFACACQACABADAAIAHgBIAAAOQgFACgJAAIgIgBgADngdIgHgCIgGgDIgFgFQgEgEgCgHQgCgGAAgIQAAgHACgGQACgGADgFQAEgFAGgDIAGgCIAHAAQAdAAAAAjIAAAFIgoAAIABAGIADAFIAFADQAEABAEAAIAKgBIAJgEIABAPIgLADIgLABgAD1hFQAAgIgCgEIgDgEQgCgBgDAAQgLAAAAARIAVAAIAAAAgACugeQgEgBgCgCQgDgDgCgDQgBgEAAgGIAAgiIgLAAIAAgOIALAAIAAgOIAUgHIAAAVIAOAAIAAAOIgOAAIAAAfQAAAFACACQACABADAAIAHgBIAAAOQgFACgJAAIgIgBgABiggIABgQIAIAEIAJABQAGAAACgCQABgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgCgEgCIgKgEIgGgDIgEgEIgDgGQgCgEAAgEIACgGQABgEADgDQADgDAEgCQAGgCAHAAQAIAAALACIgBAQQgKgEgGAAQgEAAgCACQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAADADACIALAFQAHACADAEQACACABADIABAIQAAAGgCAEQgBAEgEADIgIADIgKABQgPAAgHgDgAA4gdIgHgCIgGgDIgFgFQgEgEgCgHQgCgGAAgIQAAgHACgGQACgGADgFQAEgFAGgDIAGgCIAHAAQAdAAAAAjIAAAFIgoAAIABAGIADAFIAFADQAEABAEAAIAKgBIAJgEIABAPIgLADIgLABgABGhFQAAgIgCgEIgDgEQgCgBgDAAQgLAAAAARIAVAAIAAAAgAgLgeIgGgDQgDgDgCgFIgBAAIAAALIgUAAIABgPIAAhSIAUAAIAAAoIABAAQACgFAEgDIAFgDIAGAAQAFAAAFACQAEADADAEQADAFACAGIABANQAAAIgCAHQgBAGgDAFQgDAFgFADQgEACgFAAQgEAAgDgBgAgQhTIgEAFIgBAHIgBAHQAAAIACAFQACAEACABQACACADAAQADAAACgCIADgFQACgEAAgJIgBgHIgBgHQgBgDgCgCQgCgBgDAAQgDAAgCABgAh5gdIgHgCIgGgDIgFgFQgEgEgCgHQgCgGAAgIQAAgHACgGQACgGAEgFQAEgFAFgDIAGgCIAHAAQAeAAAAAjIAAAFIgoAAIABAGIADAFIAFADQADABAEAAIALgBIAJgEIAAAPIgLADIgKABgAhqhFQAAgIgCgEIgEgEQgCgBgDAAQgKAAAAARIAVAAIAAAAgAixgeQgEgBgDgCQgDgDgBgDQgCgEAAgGIAAgiIgLAAIAAgOIAMAAIAAgOIAUgHIAAAVIANAAIAAAOIgNAAIAAAfQAAAFACACQABABAEAAIAGgBIAAAOQgEACgKAAIgHgBgAkBgfQgEgBgCgEIgEgIIgBgJIAAgsIAVAAIAAApQAAAGACADQACACAEAAQAFAAACgEQACgEAAgHIAAglIAUAAIAAA1IABAOIgTAAIAAgLIgBAAQgCAGgEADQgDACgDAAIgHABQgFAAgEgCgAk5gdIgHgCIgGgDIgFgFQgEgEgCgHQgCgGAAgIQAAgHACgGQACgGAEgFQAEgFAFgDIAGgCIAHAAQAeAAAAAjIAAAFIgoAAIABAGIADAFIAFADQADABAEAAIALgBIAJgEIAAAPIgLADIgKABgAkqhFQAAgIgCgEIgEgEQgCgBgDAAQgKAAAAARIAVAAIAAAAgAE5geIAAhhIAUAAIAABhgAEVgeIAAhhIAUAAIAABhgAl2geIAAglIgWAAIAAAlIgVAAIAAhaIAVAAIAAAkIAWAAIAAgkIAWAAIAABag");
	this.shape.setTransform(60.2,24.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// back
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFED00").s().p("ApXkVISvAAIAAHLIyvBgg");
	this.shape_1.setTransform(60,27.8,1,1,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_stoerer, new cjs.Rectangle(0,0,120,55.5), null);


(lib.mc_sternchentext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = getMCSymbolPrototype(lib.mc_sternchentext, null, null);


(lib.mc_mouseover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AClBiQgEgBgEgEIgDgKQgCgFAAgHQAAgHACgFQABgHACgCIAIgHQAEgCAGAAQAFAAADACQAEACACAEQADADACAFQABAGAAAGIAAAGIgiAAQABAEACAEIACAFIAEAFIAIABQADAAAEgCQADgBADgDIABAKIgIACIgIABQgGAAgFgDgAC5BDIgBgIIgCgHQAAAAgBAAQAAgBAAAAQgBgBAAAAQgBAAgBAAIgEgBIgFABIgDACIgCAGQgCAEgBAFIAYAAIAAAAgACFBkQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBgBAAAAIgCgEIgCgHIAAglIgJAAIAAgIIAJAAIAAgMIAJgDIAAAPIANAAIAAAIIgNAAIAAAiQAAAEACADQACACADAAIAGgBIAAAHIgIACIgGgBgABMBkIgFgDQgCgDgCgDQgBgDAAgEQAAgEABgDQACgFAEgCQADgDAEgBQAGgCAIAAIAFAAIAAgCIgBgFIgCgFQAAAAAAAAQAAgBgBAAQAAgBgBAAQAAAAgBAAIgGgBQgFAAgDACQgFABgBADIgCgKIAIgDIAJgBQAIAAAIAFIADAFIABAKIAAAnIgIAAIgBgIQgCAEgEACIgFACIgFABIgHgBgABVBIIgGADQgCABgBADIAAAFQgBAEADADQADADAEAAIAGgBIAEgEIACgEQACgCAAgEIAAgIIgHAAIgHABgAgeBiQgEgBgDgEQgDgFgBgFQgCgFAAgHQAAgHACgFQABgHADgCQADgFAEgCQAFgCAGAAQAGAAAEACQAEACADAFQACACACAHIABAMIgBAMQgCAFgCAFQgDAEgEABQgEADgGAAQgGAAgFgDgAgaAzIgEADIgCAHIgBAKIABAJIACAIIAEAEIAHABIAGgBIAEgEIACgIIABgJIgBgKIgCgHIgEgDQgDgCgDAAIgHACgAAuBkIAAgmIgCgFQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgFgBIgEABQgDAAgCACIgCAGIgBAGIAAAjIgJAAIAAg6IAIAAIABAJQADgFADgDQAEgCAFAAIAIABIAEADQACADABADQACAEAAAFIAAAogAhBBkIAAhEIgWBEIgIAAIgWhEIAABEIgKAAIAAhQIAQAAIAUBAIAAAAIAVhAIAPAAIAABQgAjVBkIAAgJIANgPIAJgOQAFgHACgEIABgKIgBgFIgBgDQgCgDgDgBIgEgBIgJACIgHAEIgBgKQAFgDAFAAQAFgCAEAAQAEAAAEACQADABAEAEQADACAAAEQACADAAAFQAAAFgDAGQgBAGgFAHQgDAHgHAHQgEAHgHAGIAfAAIAAAJgAj5BkIAAhEIgKALIgFgIIAQgPIAKAAIAABQgADxAuIgKAUIgQgMIAQgQIgVgDIAFgTIAUALIgDgWIASAAIgCAWIASgLIAHATIgXADIAQAQIgQAMgACqgMIgFgFQgCgBgCgEIAAgIIAAgpIAIAAIAAAnIABAFIACAEIAEADIADAAIAFAAIAEgDIADgGIABgGIAAgkIAKAAIAAA7IgJAAIAAgJIgBAAQgCAFgEACQgDACgGABIgHgBgABQgMIgEgCQgCgDAAgCIgBgHIAAglIgKAAIAAgIIAKAAIAAgMIAKgCIAAAOIALAAIAAAIIgLAAIAAAiQAAAFABADQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIAGAAIAAAHQgDABgFABIgGgBgAAXgMIgFgEQgCgCgBgDQgBgEAAgEQAAgDABgEQACgEADgDIAIgEQAGgBAHAAIAGAAIAAgDIgBgFIgCgDQgBgDgCgBIgHgBQgEAAgEACQgEACgCADIgCgKIAIgEIAJAAQAIAAAIAFIAEAEQABAFAAAFIAAAoIgIAAIgBgIQgDADgDADIgEACIgGABIgIgBgAAggoQgDAAgCACIgDAEIgBAFQABAEACAEQACACAFAAIAGgBIAEgDIADgFQABgDAAgDIAAgHIgHAAIgIABgAhSgOQgFgBgDgFQgCgEgCgFQgBgFAAgIQAAgGABgGQACgGACgDQADgEAFgDQAFgBAFAAQAHAAADABQAFADADAEIAFAJIAAAMIAAANQgCAFgDAEQgDAFgFABQgDACgHABQgFgBgFgCgAhOg+IgEAEQgCACgBAEIAAAKIAAAKIADAHIAEAFIAGAAIAGAAIAEgFQACgDABgEIABgKIgBgKQgBgEgCgCIgEgEQgCgCgEAAQgDAAgDACgAjZgLIAVhSIAIAAIgVBSgAjtgMIgGgCQgFgDgFgDQgEgEgCgFQgCgGgBgHIgKAAIABgFIAIAAIAAgKIgJAAIABgGIAJAAQAAgHAEgEIAFgKQAFgFAFgCIANgCIAHABIAGACIgBAJQgCgBgEgBIgFgBQgFAAgEABQgEACgDADQgDACgBAFIgDAIIAfAAIgBAGIgfAAQgBAFABAFIAdAAIgCAFIgaAAIADAIQACAEACADQADADAEACQAEABAFABIAFgBIAGgCIABAJQgIACgFABgADXgMIgBg7IAJAAIABAJIADgEIAEgEIAEgBIAGAAIAAAJIgDAAIgFAAIgEAFIgDAFIgCAIIAAAggACFgMIAAgzIgJAAIAAgIIAJAAIAAgMIABgHIADgFQABgDADgBQADgBAEAAIAIABIAAAJQgCgBgEgBQgEAAgCACQgCADAAAEIAAAMIAMAAIAAAIIgMAAIAAAzgAgGgMIAAgmIgBgGQAAgBAAAAQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIgEgBIgFABQgCABgCACIgDAFIgBAHIAAAjIgIAAIgBg7IAJAAIAAAJQADgFAEgDQAEgBAFAAIAHAAIAFAEQABACABADQACAFAAADIAAAqgAh2gMIAAhFIgWBFIgHAAIgWhFIAABFIgKAAIAAhQIAPAAIAUA/IABAAIAVg/IAOAAIAABQgAC5hTIAAgLIAKAAIAAALgACnhTIAAgLIAJAAIAAALg");
	this.shape.setTransform(27.9,8.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_mouseover, new cjs.Rectangle(0.7,-1.3,54.5,20.2), null);


(lib.mc_head = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGFDZIAAiSIgiAAIAAgfIBsAAIAAAfIgjAAIAACSgAFDDZIgLgnIgxAAIgMAnIgkAAIA1ixIApAAIA1CxgAExCUIgQhLIgBAAIgTBLIAkAAgAB2DZIAAixIAmAAIAACRIA1AAIAAAggAAPDZIAAixIBYAAIAAAeIg0AAIAAArIAyAAIAAAeIgyAAIAABKgAiLDZIAAiSIgjAAIAAgfIBsAAIAAAfIgjAAIAACSgAkTDZIAAixIBdAAIAAAeIg4AAIAAAnIA1AAIAAAgIg1AAIAAAtIA7AAIAAAfgAlWDZIguiAIAACAIghAAIAAixIAsAAIAuB7IABAAIAAh7IAhAAIAACxgAg7CfIAAgeIA4AAIAAAegAk2gNQgLgFgJgJQgGgHgFgMQgFgKAAgOIABgLIAEgOQAEgJAFgHQAIgIALgHQgGgGgFgHQgEgIgCgHQgDgIAAgHQAAgHADgGQABgKAGgFQAHgIAKgFIALgFIARgBQAJAAAKACQAIADAIAGQAIAFAEAIQAEAKAAAMQAAAKgEAJQgEAJgGAIQgIAIgKAIIAXAiQAHgLACgcIAjAAQgBAZgEALIgQAhIAcAqIgsAAIgLgRIgJAKIgKAGQgLAFgNAAQgPAAgMgFgAkxhGQAAAJAFAJQAEAFAGADQADACAGABQAJgBAFgCQAGgEADgEIgkgvQgLAOAAAPgAkmi3QgEAFAAAJQAAAGAIALIAIANIAPgPQAFgJABgHQgDgTgPAAQgJABgGAFgAEggMIAAjJIAqAAIAACmIA7AAIAAAjgACrgMIAAjJIAqAAIAACmIA8AAIAAAjgABzgMIgNgsIg3AAIgOAsIgnAAIA8jJIAtAAIA7DJgABfhbIgUhTIAAAAIgVBTIApAAgAiNgMIAAiUIgWAYIgTgfIAyguIAhAAIAADJgAmkgMIAAiUIgYAYIgTgfIA0guIAhAAIAADJgAGPhNIAAgjIBAAAIAAAjg");
	this.shape.setTransform(51.5,24.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_head, new cjs.Rectangle(5.2,2.4,92.7,43.4), null);


(lib.mc_flathaken = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// haken
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFED00").ss(2,1,1).p("AiTAtIAEgCIATgFIAKgEIAYgHIAFgBIA9gTIAagHIAVgGIADgBIAZgIIASgGIAJgDIAsgMIAagH");
	this.shape.setTransform(87.2,144);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFED00").ss(3,1,1).p("AoPAgQAigIAogHQAZgEAagFQALgBAKgBQCKgTDBgKQEfgPEjAO");
	this.shape_1.setTransform(50.3,122.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#134094").s().p("AgJADIgCgBIAXgHQAAABAAAAQAAABAAABQgBAAAAAAQgBABAAAAIgCAEIAAAAQgEADgEAAQgEAAgFgDg");
	this.shape_2.setTransform(91.1,143);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#B0D0EF").s().p("AASBAIAJgpIAYAAIgNApgAg1AqIACgVQAIAGAIAAQAGAAAGgEQAEgCADgFIACgIIABgKQgDAEgFACQgFADgEAAQgHAAgGgDQgFgCgDgEQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgDgEgBgFQgCgHAAgIQAAgHADgHQACgHAEgDQAFgGAFgDIAOgBIALABQAEAAAFADQAEACABAEQAEABACAFQAFALAAAGQADAHAAAMIAAAGIgBAFIgaAIIAagIIgCAHQgBAMgEAHQgCAFgEABQgBAGgFABIgLAGIgMABQgMAAgLgEgAgegpQgBAFAAAHQAAAIABADQABAHAGAAQAFAAACgHIABgLIgBgMQgCgEgFAAQgGAAgBAEgAhoAuIAAgMIAAg/IgPAPIgMgVIAhgYIAXAAIAABWIgFABIgYAGIAYgGIAFgBIAAATgAhLAbgABYAGIAAgMIACABQAFADAFAAQAFAAACgDIABAAQADgCABgDQACgEAAgJQgBAFgEAAIgGABIgIgBIgGgFIgBgBIAsgLIAAAGIgBAMIgDAMIgBADIgEAEQgCACgDABQgDACgEABIgIABQgHAAgIgDgAAjAGIABgLIAAgBIACABQAFADAFAAQAEAAAEgDIABAAIABgFQABgBAAAAQABAAAAgBQAAAAABgBQAAAAAAgBIASgGIgSAGIABgJIgBAAQgCAFgCAAIgHABIgIgBIgGgFQgCgDAAgDQgCgGAAgGQAAgEACgDQAAgFAEgEIAHgFIAIgBIAIABQACAAAEADIAEACIACAFIAFALIABAMIAAAJIgBADIgDAMIAAADIgEAEIgEADIgJADQgCABgGAAQgHAAgIgDgAAzgwQgCADAAAFQAAAFACADQABADAEAAQACAAABgFQACgBAAgGQAAgEgDgDQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQgEAAgBADgAAMAAIAAAAgABYgYIgEgFIAAgMQAAgEACgDQABgFAEgEIAFgFIAKgBIAHABQADAAACADQAEAAABACIAEAFQAEAHAAAEIABAGIgsALgABngwQgBADAAAFQAAAFABADQABABAAAAQABABAAAAQABAAAAABQAAAAABAAQAEAAACgFIAAgHIgBgHQgBgDgEAAQgBAAAAAAQAAABgBAAQAAAAgBABQAAAAgBABgACEgjIAAAAg");
	this.shape_3.setTransform(86.2,143.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhrHtIABgQIAIAEQAFACAEAAIAIgCIAEgGIAAgDQAAgJgQgGIgFgDQgDgBgDgDIgDgIIgBgKIAAgDQABgFADgFIADgEIAFgDIAHgBQADgDAFAAQAGAAAMADIAAASIgIgFIgJgBQgDAAgDABQgDAFAAACIAAAHIADADIARAJQAEABACADIACAIQACADAAAHQAAAGgDAFIgEAJIgJAEIgLAAQgKAAgLgDgAihHvQgEgCgDgEQgFgEgBgHQgCgGAAgHIAAg2IASAAIAAA5IAAAGIACAEQAAABABAAQAAABAAAAQAAAAABAAQAAABABAAIAEABIAGgBIACgDQABgBAAAAQABgBAAAAQAAgBABAAQAAgBAAAAIAAgGIAAg5IASAAIAAA2QAAAHgBAGQgCAHgFAEQgDAEgFACQgGABgHAAQgGAAgGgBgACWHwIAAhVIAcAAIANABIAFADIAHAEQAAAEADADIADAGIADAJIABAMQAAAGgBAEIgDAKIgDAIIgFAEIgGAHIgGABQgJADgEAAgACoHhIAGAAQAGAAACgDQAEgBACgEQAEgEAAgEIABgMIgBgMQAAgEgEgGQgCgDgEgBQgEgDgFAAIgFAAgAByHwIgVg9IgBAAIAAA9IgQAAIAAhVIAWAAIAWA6IAAg6IAQAAIAABVgAAzHwIgGgVIgYAAIgGAVIgQAAIAYhVIAVAAIAZBVgAAYHPIASAAIgJgkgAgvHwIAAhVIASAAIAABGIAaAAIAAAPgAjKHwIgEgVIgZAAIgFAVIgSAAIAahVIATAAIAZBVgAjkHPIASAAIgIgkgACyApIAAhGIgQAAIAAgPIA0AAIAAAPIgSAAIAABGgABuApIAAhVIAtAAIAAAPIgcAAIAAATIAaAAIAAAOIgaAAIAAAVIAeAAIAAAQgABLApIgWg9IgBAAIAAA9IgQAAIAAhVIAVAAIAXA7IAAg7IAQAAIAABVgAAIApIgJgdIgBgGIgJAAIAAAjIgSAAIAAhVIAcAAIAJAAQAEACADADQAFACABADQACAGAAAHQAAARgPACQADABACAEQACADADAGIAJAdgAgLgIIAGAAIAEgBIACgCQADgDAAgGIgBgGIgDgDQgCgBgDAAIgGAAgAhWApIAAhVIAtAAIAAAPIgcAAIAAATIAbAAIAAAOIgbAAIAAAVIAeAAIAAAQgAiDApIAAhGIgQAAIAAgPIAzAAIAAAPIgPAAIAABGgAiwApIgWg9IgBAAIAAA9IgQAAIAAhVIAVAAIAXA7IAAg7IAQAAIAABVgAj3ApIAAhVIASAAIAABVgAAzmXIgHgCQgEgBgBgEQgDgBgDgEIgEgGIgBgIIgCgRIACgRIABgJQADgDABgDQADgCADgEIAFgDQADgDAEAAQADgCAEAAQAFAAADACQAEAAADADIAFADIAFAGIAFAGIABAJIABARIgBARIgBAIQgCAEgDACQgCAEgDABQgCAEgDABIgHACIgIAAIgHAAgAA0neIgFAIQgCADAAAGQgBAEAAAHIABALQAAAGACADIAFAHQADACADAAQAEAAAEgCQACgBABgGIAEgJIAAgLIAAgLIgEgJQgBgGgCgCQgEgDgEAAQgDAAgDADgADSmXIAAhXIAtAAIAAAQIgcAAIAAAUIAbAAIAAAOIgbAAIAAAXIAcAAIAAAOgACwmXIAAhXIATAAIAABXgACPmXIgXg/IAAAAIAAA/IgRAAIAAhXIAXAAIAVA9IAAg9IARAAIAABXgAgYmXIAAhXIApAAIAAAQIgYAAIAAAUIAXAAIAAAPIgXAAIAAAkgAhSmXIAAhXIAtAAIAAAQIgaAAIAAAUIAZAAIAAAOIgZAAIAAAXIAbAAIAAAOgAiGmXIAAhXIARAAIAABHIAZAAIAAAQgAi/mXIAAhXIAsAAIAAAQIgbAAIAAAUIAZAAIAAAOIgZAAIAAAXIAdAAIAAAOgAjsmXIAAhHIgQAAIAAgQIAzAAIAAAQIgRAAIAABHg");
	this.shape_4.setTransform(57.2,62.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F8EF1A").s().p("ACZIdIAAiRIgjAAIAAghIBrAAIAAAhIgiAAIAACRgABZIdIgJgoIg0AAIgLAoIgiAAIAziyIAqAAIA0CygAAlHXIAiAAIgQhJIAAAAgAhyIdIAAiyIAmAAIAACRIA2AAIAAAhgAjfIdIAAiyIBYAAIAAAgIg0AAIAAApIAxAAIAAAfIgxAAIAABKgACZBVIAAiPIgjAAIAAghIBrAAIAAAhIgiAAIAACPgABZBVIgJgnIg0AAIgLAnIgiAAIAziwIAqAAIA0CwgAAlAQIAiAAIgQhJIAAAAgAhyBVIAAiwIAmAAIAACRIA2AAIAAAfgAjfBVIAAiwIBYAAIAAAfIg0AAIAAApIAxAAIAAAeIgxAAIAABKgACZlqIAAiSIgjAAIAAggIBrAAIAAAgIgiAAIAACSgABZlqIgJgnIg0AAIgLAnIgiAAIAziyIAqAAIA0CygAAlmvIAiAAIgQhLIAAAAgAhylqIAAiyIAmAAIAACSIA2AAIAAAggAjflqIAAiyIBYAAIAAAgIg0AAIAAAoIAxAAIAAAgIgxAAIAABKg");
	this.shape_5.setTransform(54.3,44.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFED00").s().p("AhIN7IAWhuIBBAAIgiBugAj7NmIAEg3QAXANAXgBQARAAANgGQALgIAHgMQAIgPACggIgBAAQgHAMgNAGQgLADgPAAQgRAAgPgFQgNgHgKgMQgKgOgFgRQgFgSAAgWQAAgUAGgRQAGgRALgMQANgMAPgGQAJgEAKgBQAJgCAJAAQAKAAAJACIAJACQAMACALAGQAKAFAIAIQAHAIAGAKQANAcAEAQQAEAWAAAdQAAAagEAWQgIAkgIAPIgGAKIgEAGIgFAFIgLALIgKAHQgMAHgOAFQgPADgTABQgcAAghgLgAi9KKQgFALAAAUQAAAVAFAIQAGALAMAAQANAAAGgMQAFgKAAgTQAAgUgFgKQgGgMgNAAQgMAAgGAMgAkwNnIgFgEIgDAFIgMAAIAAhOIAPAAIAAAZQAFgFAHAAQAGAAAEACQAEABADAEIAFAKQABAFAAAHQAAAHgBAFQgCAGgDAEQgDAEgEACQgEACgGAAQgEAAgDgCgAkxM7IgEADIAAAaIAEAEQAAAAABABQAAAAABAAQAAAAABAAQAAABABAAQAGAAACgGQADgEAAgJQAAgIgDgFQgCgEgGAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBABAAAAgAl4NlQgDgDgBgDIgBgIQAAgGAEgFQAEgFAIgCIALgBIAGAAQAAgHgDgCQgCgBgHAAIgHAAIgHABIgCACIAAgLQAJgEAJAAQAHAAAFABQAFABACADQAGAFAAAMIAAAkIgLAAIgDgHQgDAEgEACQgDACgGAAQgHAAgGgEgAlqNPQgEADAAAEQAAAEACACQADABADABQADAAAEgDIACgEIABgFIAAgFIgDAAQgIAAgDACgABhLkIACggQAMAJAOAAQALAAAHgGQAGgDAEgIQAFgIABgSIgBAAQgEAGgHADQgHADgIAAQgLAAgIgEQgIgEgGgGQgGgIgCgKQgDgMAAgMQAAgMADgJQAEgKAHgHQAEgFAGgDIAFgDIABAAIAHgDQAHgBAHgBQAIABAHABIABAAIAIADIAGADQAGADAEAFIABABIAIAJIAJAaQACAMAAARQAAAQgCANQgFAUgEAJQgEAHgEAFIgBABQgGAFgGAEQgHAFgJADQgJABgLAAQgQAAgSgGgACFJlQgEAFAAAMQAAAMAEAGQADAHAHAAQAIAAADgIQADgFAAgMQAAgLgEgHQgDgGgHAAQgHAAgDAHgAgbLkIADggQAMAJANAAQAKAAAIgGQAGgDAEgIQAFgIABgSIgBAAQgEAGgHADQgHADgIAAQgKAAgIgEQgIgEgFgGQgGgIgDgKQgEgMAAgMQAAgMAEgJQAEgKAHgHQAEgFAGgDQADgBACgCIAAAAIAHgDQAHgBAHgBQAIABAHABIABAAIAJADIAEADIABAAQAGADAEAFQAFAEADAGQAIARACAJQACAMAAARQAAAQgCANQgFAUgFAJQgEAHgFAGQgFAFgGAEQgHAFgJADQgJABgLAAQgPAAgTgGgAAJJlQgEAFAAAMQAAAMADAGQADAHAIAAQAIAAADgIQADgFAAgMQAAgLgEgHQgDgGgHAAQgIAAgCAHgAEsLfQgLAAgLgFQgJgDgHgHQgIgHgEgLQgFgJgCgLIgTAAIACgOIAOAAIAAgPIgQAAIACgOIARAAQACgLAEgJQAFgKAIgHQAGgHAKgEQAJgFALAAIASABQAJACAJAEIgHAaQgEgDgHgBIgKgBQgGAAgEADQgFAAgDAEQgEADgCAEQgEAFgBAGIAtAAIgEAOIgsAAQgBAHABAIIAqAAIgEAOIgjAAQABAFAEAFIAGAIIAIAEQAGADAEAAIAKgBIALgEIABAdIgNAEgAFqJWIgGANIgLgJIALgKIgNAAIACgMIAOAGIgCgOIAMAAIgDAOIAMgGIAEAMIgNAAIAJAKIgJAJgAjaD7IgIAAIgGgHIgFgIIgOgWIgNgXIgEgGIgPgYQgMgQAAgDQAAgEAGgEIALgIQALgHAKAAIAGACQAEACABADIASAfIAKAQQABAGADAAQADACAHgNIAUghIAQgcQAMgVAJgJIAQgVIALgKQALgLAHgEQADgDAIgDQALgGACgDIAQgCIAJABIAEABIAEAAIADADIgBADQggAcgWAbIgQAWIgNAUQgOAVgRAfIgLAUIgSAiIgDAEIgEAGQgEAIgEAEIgIAEIgEABIgFgBgAjajLIgIgBIgGgGIgFgIIgOgWIgRgdIgPgXIgMgTQAAgFAGgFIALgJQALgHAKAAQACAAAEAEIAFAFIASAeIAKASQABAEADAAQADADAHgOIAUgfQAKgTAGgJQAMgWAJgKQAJgMAHgIIALgKQALgMAHgEQADgDAIgEIANgHQAGgCAKgBIAJABIAEACIAEAAIADADIgBACQggAcgWAbIgQAXIgNAUQgOAUgRAgIgdA1IgDAFIgEAGQgEAIgEAEIgIAEIgJAAgAjaqLQgGAAgCgCIgGgFQAAgCgFgGIgOgYQgLgUgGgHIgPgXQgMgRAAgDQAAgEAGgFIALgJQALgHAKAAQACAAAEADIAFAGIASAeIAKASQABABAAAAQAAABABAAQAAABABAAQAAAAABAAQADACAHgNIAUgfIAQgdQAMgVAJgIQAJgOAHgHQADgEAIgHIASgPQADgEAIgDIANgHIAQgEIAJABIAEACIAEABIADADIgBACQggAcgWAcIgQAUIgNAUQgOAWgRAhIgdAzIgDAFIgEAGQgEAIgEADQgDADgFACIgGABIgDAAg");
	this.shape_6.setTransform(33,75.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_flathaken, new cjs.Rectangle(-5.1,-13.3,109.7,178.2), null);


(lib.label_neu = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// typo1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#134094").s().p("ABrBQQgGgBgFgDQgKgEgGgHQgFgHgDgJIgEgRIgBhwIAhAAIAABmQAAAOAEAHQAFAHALAAQAKAAAEgHQAGgHAAgOIAAhmIAgAAIAABhQAAAggOAQQgMAQgaAAgAghBPIAAifIBTAAIAAAeIg1AAIAAAiIAuAAIAAAdIguAAIAAAkIA1AAIAAAegAhgBPIgthuIAABuIgeAAIAAifIAnAAIAuBuIAAhuIAcAAIAACfg");
	this.shape.setTransform(26.6,19.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// bg1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFED00").s().p("AjtB1IAAjpIHbAAIAADpg");
	this.shape_1.setTransform(26.5,19.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.label_neu, new cjs.Rectangle(2.8,8,47.6,23.4), null);


(lib.head_24h = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABUA7QgEgCgDgEQgGgHAAgKIAAgvIgOAAIAAgRIAOAAIAAgTIAYAAIAAATIASAAIAAARIgSAAIAAArQAAAFACADQADADAEgBIAJAAIAAARQgJACgJAAQgGAAgFgCgAGDA6QgHgDgGgGQgKgNAAgVQAAgVAKgMQAGgFAHgEQAHgCAJAAIANAAIAKADIAAATQgKgDgHgBQgFABgEABQgDACgDADQgFAFAAAOQAAAOAFAGQADADADACQAEABAFABQAHgBAKgDIAAATIgKADIgNAAQgJAAgHgCgAEoA4IAAgUQAOAGAKAAQAFAAADgCQADgCgBgEQABgDgEgDQgDgDgIgDIgIgFIgGgEQgCgDgCgFQgCgDAAgFQAAgMAJgHQAJgIANABQAKAAAMACIAAASQgMgDgHAAQgGAAgCACQgCADgBADQAAAEACAAIALAGIAJAFIAHAFQADADACAEQACAEAAAFQAAAOgJAHQgFAEgFACQgHACgHgBQgNAAgNgEgADaA1QgEgEgCgFQgBgFAAgHIAAg8IAYAAIAAA6QAAAGACADQACACAFABQAEAAADgCQADgCADgEIAAg+IAYAAIAABXIgSAAIgFgJQgEAFgGADQgFADgHgBQgLAAgHgHgACAA2QgEgDgCgGQgCgEAAgIQAAgKAHgIQAGgHAMgDQAIgBAIAAIAJAAQAAgJgEgEQgDgDgLAAIgMABIgJADIgDACIAAgSQANgFAPAAQAKAAAIABQAHACAEAEQAIAIAAASIAAA3IgRAAIgEgLQgEAGgGAEQgGACgIAAQgLAAgJgGgACUAWQgFADAAAHQAAAGAEADQADACAFAAQAFAAAFgEIAEgHIABgHIAAgHIgEAAQgMAAgGAEgAgHA4IAAgUQANAGAJAAQAGAAACgCQADgCAAgEQAAgDgDgDQgDgDgJgDIgHgFIgFgEQgDgDgCgFQgBgDAAgFQAAgMAIgHQAJgIAMABQALAAAMACIAAASQgMgDgIAAQgFAAgDACQgCADAAADQAAAEACAAIALAGIAJAFIAGAFQAEADACAEQABAEAAAFQABAOgKAHQgEAEgGACQgGACgIgBQgNAAgLgEgAhVA1QgEgEgCgFQgCgFAAgHIAAg8IAYAAIAAA6QAAAGADADQABACAGABQADAAAEgCQADgCACgEIAAg+IAZAAIAABXIgTAAIgEgJQgEAFgGADQgGADgGgBQgMAAgGgHgAHoA7IAAg7QAAgFgEgDQgCgDgGAAQgEAAgCACQgDACgCAEIAAA+IgYAAIAAh3IAYAAIAAAnQAFgEAEgDQAGgBAGAAQAFAAAFABQAEACAEAEQAIAIgBAMIAAA9gAiCA7IgHgaIgiAAIgGAaIgbAAIAkhvIAdAAIAjBvgAiPANIgLgpIgLApIAWAAgAkkA7IAAg7QAAgFgCgDQgDgDgFAAQgFAAgCACQgDACgCAEIAAA+IgYAAIAAh3IAYAAIAAAnQAEgEAGgDQAFgBAGAAQAGAAAEABQAFACADAEQAIAIAAAMIAAA9gAmFA7IAAgXIgpAAIAAgVIAlhDIAcAAIAABHIAKAAIAAARIgKAAIAAAXgAmdATIAYAAIAAgsgAn+A7IAAgVIATgSIAMgPIAFgHIADgJIABgIIgBgGIgDgEQgGgDgHAAIgHABIgPAEIAAgVQARgGANAAQAPABAKAHQAEAFADAFQACAGAAAHIgCARIgDAGIgHAOIgYAYIAmAAIAAAVgAj8AZIAAgUIApAAIAAAUg");
	this.shape.setTransform(77.4,39.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.head_24h, new cjs.Rectangle(26.3,33,102.3,12.2), null);


(lib.haken3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#134098").s().p("AA3AvQgGgDgEgFQgJgKAAgQQAAgRAJgKQAEgFAGgDQAFgCAIAAIAKABIAIACIAAAQQgIgDgGAAIgGABIgGAEQgEAEAAAMQAAAKAEAGIAGADIAGABQAGAAAIgCIAAAPIgIACIgKABQgIABgFgDgAgaArQgDgDgBgEQgBgEAAgFIAAgyIATAAIAAAvQAAAGACABQACACAEAAIAFgBIAEgEIAAgzIAUAAIAABHIgPAAIgEgIQgDAFgEACQgEADgGgBQgJAAgGgGgACIAwIAAgwQAAgDgCgDQgCgCgFAAIgFABIgEAEIAAAzIgTAAIAAhhIATAAIAAAhQAEgEAEgCQAEgCAFAAQAEAAAEABIAHAGQAGAFAAALIAAAxgAhRAwIAAhHIAPAAIADAIQAHgJALAAIAFABIAAASQgGgCgGABQgGABgEAEIAAAxgAibAwIAAhaIAhAAQAKAAAIAGQAIAGAAAKQAAAFgCAEQgCAFgDABIgFAEIgFABQAKADAFAFQAEAFAAAJQAAAJgEAGQgFAGgGADQgGACgHAAgAiHAgIAHAAQAGABAEgEIADgEIABgFIgBgGIgDgDQgEgDgGgBIgHAAgAiHgGIAGAAQAGAAAEgDQADgCAAgFQAAgGgDgCQgDgDgHAAIgGAAg");
	this.shape.setTransform(30.9,9.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#134094").s().p("AgfBBIgDgDIgDgEIgIgNQgGgMgDgDIgJgOQgGgJAAgCQAAgBADgEIAGgDQAGgFAGAAIADADIADADIAKAPIAFAKQABABAAAAQAAAAAAABQAAAAABAAQAAAAAAAAQADABADgHIALgRIAIgPQAHgMAFgFQAEgHAFgEIAGgGIAJgIQACgCAFgCIAHgEIAJgCIAFAAIACABIACABIACACIgBABQgRAPgMAPIgJAMIgHALIgSAdIgPAdIgCADIgBACQgDAFgDACIgDADIgGAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAgBg");
	this.shape_1.setTransform(7,8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.haken3, new cjs.Rectangle(0,1.4,46.5,13.3), null);


(lib.haken2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#134098").s().p("AFGAvQgGgDgEgFQgIgLAAgRQAAgIACgFQACgHAEgFQAIgKAOAAQAPAAAIAKQAHAJAAASIAAAGIgpAAQAAAFAEAFQAEAFAJgBQAKABAKgEIAAAPIgLADQgGACgGgBQgIAAgHgCgAFHAFIAXAAQAAgPgMAAQgLAAAAAPgAD6AvQgFgDgEgFQgIgKAAgRQAAgJACgGQACgGAEgFQAHgKAOAAQAJAAAGAHIAAggIATAAIAABhIgPAAIgDgHQgDAFgEACQgEABgFAAQgHAAgFgCgAD9AMQAAAXAPgBIAFgBQACgBACgDIAAghQgEgFgFAAQgPAAAAAVgACqAsQgEgDgBgEQgCgEAAgGQAAgIAGgGQAFgGAJgDIAOgBIAHAAQAAgHgDgCQgDgDgJgBIgJACIgIACIgCABIAAgOQALgFALAAQAJAAAGABQAGACADAEQAHAFAAAPIAAAtIgOAAIgEgJQgDAFgFADQgEACgHAAQgJAAgHgFgAC7ASQgFADAAAFQAAAFADACQADACAEAAQAEAAAEgEQACgCABgCIABgGIAAgGIgEAAQgJAAgEADgAAzAvQgGgDgEgFQgJgKAAgQQAAgRAJgKQAEgFAGgDQAFgCAIAAIAKABIAIACIAAAQQgIgDgGAAIgGABIgGAEQgEAEAAAMQAAAKAEAGIAGADIAGABQAGAAAIgCIAAAPIgIACIgKABQgIABgFgDgAgWAuIAAgQQALAEAIAAQADAAADgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgDgDgCQgCgDgHgCIgFgEIgFgDQgDgDgBgEQgBgDAAgEQAAgJAHgGQAHgGAKAAQAIAAAKADIAAAOQgJgDgHAAQgEABgBACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAABQABAAAAAAQAAAAABABIAHAEIAHAEIAGAEQADADABADIABAHQAAAMgHAFQgDAEgFABQgFACgFgBQgLAAgKgDgAh6AvQgHgDgEgFQgIgLAAgRQAAgIACgFQACgHAFgFQAIgKAOAAQAPAAAHAKQAIAJAAASIAAAGIgqAAQAAAFAEAFQAFAFAJgBQAJABAKgEIAAAPIgLADQgFACgGgBQgJAAgGgCgAh6AFIAXAAQAAgPgLAAQgMAAAAAPgAjEAuIAAgQQALAEAIAAQAEAAADgCQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgDgDgCIgKgFIgFgEIgFgDQgDgDgBgEQgBgDAAgEQAAgJAHgGQAHgGALAAQAIAAAKADIAAAOQgJgDgHAAQgEABgCACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAABQABAAAAAAQAAAAABABIAIAEIAHAEIAGAEQADADABADIABAHQAAAMgHAFQgDAEgFABQgFACgGgBQgLAAgKgDgAj8AuIAAgQQALAEAIAAQAEAAADgCQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgDgDgCQgDgDgHgCIgFgEIgFgDQgDgDgBgEQgBgDAAgEQAAgJAHgGQAHgGALAAQAIAAAKADIAAAOQgJgDgHAAQgEABgCACQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAABQAAAAABAAQAAAAABABIAIAEIAHAEIAGAEQADADABADIABAHQAAAMgHAFQgDAEgFABQgFACgGgBQgLAAgKgDgAk8AsQgEgDgBgEQgCgEAAgGQAAgIAGgGQAFgGAJgDIAOgBIAHAAQAAgHgDgCQgDgDgJgBIgJACIgIACIgCABIAAgOQALgFALAAQAJAAAGABQAGACADAEQAHAFAAAPIAAAtIgOAAIgEgJQgDAFgFADQgEACgHAAQgJAAgHgFgAkrASQgFADAAAFQAAAFADACQADACAEAAQAEAAAEgEQACgCABgCIABgGIAAgGIgEAAQgJAAgEADgAGhAwIAAgwQAAgDgCgDQgBgCgFAAQgGAAgEAFIAAAzIgTAAIAAhHIAPAAIADAIQAHgJALAAQAEAAAEABIAHAGQAGAFAAALIAAAxgACEAwIAAgwQAAgDgCgDQgCgCgFAAIgFABIgEAEIAAAzIgTAAIAAhhIATAAIAAAhQAEgEAEgCQAEgCAFAAQAEAAAEABIAHAGQAGAFAAALIAAAxgAhFAwIAAhHIAPAAIADAIQAIgJAKAAIAFABIAAASQgFgCgGABQgHABgDAEIAAAxgAlyAwIgMhDIgMBDIgYAAIgShaIAUAAIALA+IALg+IAYAAIALA+IALg+IAUAAIgSBag");
	this.shape.setTransform(58.3,9.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#134094").s().p("AgfBBIgDgDIgDgEIgIgNQgGgMgDgDIgJgOQgGgJAAgCQAAgBADgEIAGgDQAGgFAGAAIADADIADADIAKAPIAFAKQABABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAQADABADgHIALgRIAIgPQAHgMAFgFQAEgHAFgEIAGgGIAJgIQACgCAFgCIAHgEIAJgCIAFAAIACABIACABIACACIgBABQgRAPgMAPIgJAMIgHALIgSAdIgPAdIgCADIgBACQgDAFgDACIgDADIgGAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_1.setTransform(7,7.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.haken2, new cjs.Rectangle(0,1.2,102,13.3), null);


(lib.haken1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#134098").s().p("ACkAxQgDgCgCgDQgFgGAAgIIAAglIgLAAIAAgPIALAAIAAgPIAUAAIAAAPIAOAAIAAAPIgOAAIAAAiQgBAEACACQADACAEAAIAGAAIAAAOQgGABgIAAQgFAAgFgBgAAaAvQgHgCgEgGQgIgKAAgRQAAgIACgFQACgHAEgFQAJgKAOAAQAOAAAIAJQAHAKAAARIAAAGIgpAAQAAAGAEAFQAEAEAKAAQAJAAAKgDIAAAPIgLADQgFABgHAAQgIAAgGgDgAAaAGIAXAAQAAgPgLAAQgMAAAAAPgAhZAvQgHgCgEgGQgIgKAAgRQAAgIACgFQACgHAFgFQAHgKAOAAQAPAAAIAJQAIAKgBARIAAAGIgpAAQAAAGAEAFQAEAEAKAAQAJAAAKgDIAAAPIgLADQgFABgHAAQgIAAgGgDgAhZAGIAXAAQAAgPgMAAQgLAAAAAPgAB4AxIgVgmIAUghIAVAAIgVAhIAWAmgABPAxIAAhhIAUAAIAAA7IAAAmgAgfAxIAAg4IgLAAIAAgPIALAAIAAgIIABgGIADgGQACgDAEgCQAFgCAEAAQAJAAAFABIAAAOIgHAAQgDAAgBACQgDABAAAEIAAAFIAOAAIAAAPIgOAAIAAA4gAi7AxIAAhaIAdAAQASAAAMAMQAMAMAAAUQAAALgDAIQgDAIgGAGQgMANgSAAgAinAgIAFAAIAJgBIAIgFQADgDACgGQADgFAAgJQAAgHgDgGQgCgGgDgDIgIgEIgJgBIgFAAgABjALg");
	this.shape.setTransform(6.5,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#134094").s().p("AgfBBIgDgDIgDgEIgIgNQgGgMgDgDIgJgOQgGgJAAgCQAAgBADgEIAGgDQAGgFAGAAIADADIADADIAKAPIAGAKQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAQABABAEgHIALgRIAJgPQAGgMAFgFQAFgHAEgEIAGgGIAKgIQABgCAFgCIAHgEIAJgCIAFAAIACABIACABIACACIgBABQgRAPgNAPIgJAMIgHALIgRAdIgOAdIgDADIgCACQgCAFgCACIgFADIgEAAQgBAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_1.setTransform(-20.6,-2.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.haken1, new cjs.Rectangle(-27.6,-8.9,52.9,13.6), null);


(lib.grafik_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_18 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(18).call(this.frame_18).wait(1));

	// full
	this.instance = new lib.grafik_full_120px();
	this.instance.parent = this;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(13).to({_off:false},0).wait(6));

	// Ebene 2
	this.instance_1 = new lib.grafik_step3_120px();
	this.instance_1.parent = this;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(8).to({_off:false},0).wait(11));

	// Ebene 3
	this.instance_2 = new lib.grafik_step2_120px();
	this.instance_2.parent = this;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(3).to({_off:false},0).wait(16));

	// Ebene 4
	this.instance_3 = new lib.grafik_step1_120px();
	this.instance_3.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(19));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,120,600);


(lib.mc_glow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// shine_maske
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.8)","rgba(255,255,255,0)"],[0.298,0.51,0.765],-37,2.7,37.5,2.7).s().p("AjfINIh+wZIAhAAIAAADIIbAAIB/QWg");
	this.shape.setTransform(32.4,51.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_glow, new cjs.Rectangle(-2.6,-0.9,70,104.9), null);


(lib.mc_clickbtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// typo
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#134094").s().p("Ah3AmIABgQQAEACACAAIAEgBIADgCQACgDAAgFIAAg0IATAAIAAA0IgBALQgBAFgDAEQgDADgEACQgEACgHAAQgGAAgGgCgABkAmIgFgCQgDgCgBgEQgCgDAAgFIAAgdIgJAAIAAgMIAKAAIAAgMIASgFIAAARIAMAAIAAAMIgMAAIAAAbQAAADACACQABAAAAABQABAAAAAAQABAAAAABQABAAABAAQACAAADgCIAAANQgEABgJAAIgHgBgAAHAmQgEAAgDgCIgBgGQgCgDAAgFIAAgdIgKAAIAAgMIALAAIAAgMIAQgFIAAARIAMAAIAAAMIgMAAIAAAbQAAADACACQAAAAABABQAAAAABAAQAAAAABABQABAAAAAAQADAAADgCIAAANQgEABgJAAIgGgBgAg3AmIgFgDIgEgEQgEgEgCgFQgBgGgBgHQABgGABgEIAFgKQAEgFAFgBIAFgDIAGAAQAaAAAAAeIAAAEIgjAAIAAAFQABABAAABQAAAAABABQAAAAABABQAAAAAAAAIAFADQADABAEAAIAJgBIAIgEIAAAOQgEACgFAAIgLABgAgjAEQAAgFgCgEQgBAAAAgBQAAAAAAgBQgBAAAAAAQgBgBAAAAIgFgBQgJAAAAANIATAAIAAAAgAAgAmIAAgOIAXgdIgWAAIAAgOIApAAIAAAOIgWAeIAXAAIAAANg");
	this.shape.setTransform(23.8,35.5,1,1,0,0,0,-0.7,1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#134094").s().p("AF7ApQgCAAgCgCQgEgCgBgCQgEgEgBgFQgCgGAAgHQAAgGACgGQACgEACgEQAEgEAFgDIAGgCIAGAAQAaAAgBAeIAAAEIgjAAIABAFQABADADABQAAABAAAAQAAABABAAQAAAAABAAQAAABABAAQADABAEAAIAJgBIAJgDIAAANQgFACgFAAIgJABgAF8AIIATAAQAAgHgCgCQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAIgEgBQgKAAAAANgAERApQgDAAgBgCQgDgCgCgCQgEgEgCgFQgBgGAAgHIABgMQACgEADgEQAEgEAEgDIAGgCIAHAAQAZAAAAAeIAAAEIgjAAIABAFQABADACABQABACADABQADABADAAIAKgBIAHgDIAAANQgEACgFAAIgJABgAESAIIATAAQAAgHgDgCQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAgBAAIgDgBQgKAAAAANgAAiApQgFgCgEgEQgEgFgCgFQgBgFgBgHQABgHABgFIAGgJIAJgGIAFgCIAHAAQAEAAAIACIAJAGIAFAJQACAFAAAHQAAAHgCAFQgCAFgDAFQgEAEgFACIgMACgAAnAAIgCAFIgBAIIABAIIACAGQAAAAABABQAAAAAAABQAAAAABAAQAAABABAAIAEABIAFgBIACgDIABgGIAAgQIgBgFIgCgDIgFAAIgEAAIgDADgAHLAqIAAgkQAAgFgCgBIgFgBQgFAAgBABQgCAEAAAFIAAAhIgSAAIAAgtIgBgMIARAAIAAAKQADgGAEgCIAEgDIAHAAQAEAAAEACQAEABACADIADAHIAAAHIAAAmgAFAAqIAAgtIgBgMIARAAIAAALIAGgJIAFgCQACgBAEAAIADAAIAAAQIgGAAQgFAAgCAAQgCABgBADQgBACAAAEIgBAggADiAqIAAg5IATAAIAAA5gADDAqIAAgkIgBgGQgDgBgCAAQgFAAgBABQgCABgBAEIAAAlIgSAAIAAgkQAAgFgBgBIgFgBIgEAAIgBABQgDAEAAAFIAAAhIgSAAIAAgtIgBgMIARAAIAAAKQADgGADgCIAGgDIAGAAIAGAAIAEACQADADADAFQACgFADgDIAEgCIAHAAQAFAAAEACQADABACADQACADABAEIABAHIAAAmgABVAqIAAgtIgBgMIARAAIAAALIAGgJIAFgCIAGgBIAEAAIAAAQIgHAAQgDAAgDAAQgCABgBADQgCACAAAEIgBAGIAAAagAgRAqIAAgtIgLAAIAAgMIALAAIAAgKIAAgGIADgGIAGgEIAIgBIAMABIgBANIgEgBQgEAAgCABQgBABAAAFIAAAHIALAAIAAAMIgLAAIAAAtgAg1AqIAAgkQAAgFgCgBQgBgBAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQgFAAgBABQgCAEAAAFIAAAhIgSAAIAAgtIgBgMIAQAAIABAKQADgGAEgCIAEgDIAGAAQAFAAAEACQAEABACADQACADAAAEIABAHIAAAmgAh1AqIAAg5IASAAIAAA5gAnFARIAQgOIgQgOIAAgJIAWATIAAAHIgWAUgAncARIARgOIgRgNIAAgKIAWAUIAAAHIgWATgADigaIAAgPIATAAIAAAPgAh1gaIAAgPIASAAIAAAPg");
	this.shape_1.setTransform(51.8,33.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// back
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFED00").s().p("AoZBuIAAjbIQzAAIAADbg");
	this.shape_2.setTransform(52.5,33.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_clickbtn, new cjs.Rectangle(-1.2,22.8,107.5,22.1), null);


(lib.maushand_vector = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// maushand_vektor
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(51,51,51,0.447)").s().p("AgtAVIAJgFIAAAAIAFAIIgJAFgAAlgPIgFgIIAAAAIAJgFIAFAIIgJAFg");
	this.shape.setTransform(15.5,17.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AgGgBIAIgFIAFAIIgIAFg");
	this.shape_1.setTransform(6.7,13);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E5E5E5").s().p("AgCAZIAHgFIAAAAIAGAIIgJAFgAgEACIAIgEIAGAIIgJAFgAgKgbIAJgFIAEAIIgHAFg");
	this.shape_2.setTransform(17.1,11);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AASBVIAIgGIgFgJIgIAGIgGgIIgIAEIAAAAIAIgFIgEgIIgIAEIgGgIIgIAFIAAgBIAIgFIgEgIIgJAFIgFgIIgJAFIAAAAIgKgRIgJAEIAAAAIAJgFIgEgIIgJAEIgGgIIAJgFIAJgFIAKARIAFAJIAJgFIgGgJIg2heIARgKIAoBFIAIgFIgOgaIARgKIAPAaIAHgFIgJgRIARgKIAPAaIAJgFIgKgRIAJgGIAEAJIAJgFIAUAjIgJAFIAGAIIAEAJIAFAIIgJAEIAGAJIAEAJIAJgFIAAABIgJAEIAAAAIgIAFIAFAJIAFAJIAIgGIAAABIhEAoIAAAAgAhGAgIAJgGIAAABIgJAFgAhQAOIAJgFIAEAJIgIAFgAhDASg");
	this.shape_3.setTransform(10,10.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CCCCCC").s().p("AAPBQIAIgFIAFAJIgIAFgAgDBEIAIgFIAFAJIgJAFgAgWA4IAJgFIAFAIIgIAFgABLAtIAJgFIAFAJIgIAFgAg7AgIAAgBIAJgFIAFAJIgJAFgAhIAcIAIgFIAFAIIgJAFgABKAXIAJgFIAFAJIgJAFgAhFAOIAJgFIAFAJIgJAFgABEgHIAIgFIAGAJIgJAEgAglgyIASgKIAEAJIgRAKgAgGg4IARgKIAFAJIgRAKgAAmg7IAIgFIAGAJIgJAFgAAYg+IAJgFIAFAIIgJAFgAAmg7gAhYhOIASgKIAEAJIgRAKg");
	this.shape_4.setTransform(9.8,9.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAZBhIgFgIIAAAAIBFgnIAFAIIAAAAIAAAAIhFAnIAAABgAAKBeIgEgJIgFgIIAJgFIAFAIIAFAJIgJAFgAgMBJIgFgIIAJgGIAFAJIAEAJIgIAEgAgeA8IgFgIIAIgEIAFAIIAFAIIgIAFgAgxAxIgFgJIAJgFIAKARIgJAFgABUAoIgFgIIAJgFIAFAIIAFAJIgJAFgAhEAkIAJgEIAFAIIgJAEgAhbAPIAKgGIAJgFIAHgEIAAAAIAFAIIgJAGIgJAEIAFAJIAFAJIgIAFgAgvANIgIAEIgFgJIAAAAIAAABIAIgFIgthOIAJgEIgFgJIARgKIAFAIIgRALIAFAJIA3BdIgJAGgABTASIgFgJIgFgJIAIgDIAFAHIAKASIgIAEgABMgMIgFgIIgUgkIgFgIIAJgFIAjA8IgJAGgAhChQIgFgJIAJgEIAPAaIAFAJIAJgGIAIgEIAFAIIgRAKIAFAJIAPAaIgJAEgAgPgzIgFgJIAJgFIAQgKIAFAJIgQAJIAFAJIAJASIgIAEgAAPg5IgFgJIAJgGIAJgEIAFAJIgJAEIAFAJIAKARIgJAGgAAhhDIAIgGIAFAJIgIAFgAAKhCg");
	this.shape_5.setTransform(9.8,9.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(153,153,153,0.498)").s().p("AgTBOIAJgFIAAAAIAFAIIgJAFgAglBBIAIgFIAAABIAFAIIgIAFgAg4A1IAJgFIAAABIAFAIIgJAFgAhLApIgIAFIgFgJIAIgFIAAABIAFAIIAJgFIAAAAIAFAJIgJAFgABMAXIAAAAIAIgFIAFAIIgIAFgAhIAFIgFgHIAAgBIAAAAIAFAIgABFgHIAJgFIAFAIIgJAEgAg7hHIAJgFIAFAJIgJAFgAglhIIAJgFIAFAIIgJAFgAAdhMIAJgFIAFAIIgJAFgAgGhPIAIgFIAFAJIgIAFgAAQhQIAIgFIAFAJIgIAFgAAdhMg");
	this.shape_6.setTransform(11,10.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.maushand_vector, new cjs.Rectangle(0,0,20.1,20.1), null);


(lib.mc_head_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ABICfIAXg4IgthnIAbAAIAfBIIAchIIAaAAIhACfgAiVBrQgMgGgFgFIgHgIIgGgKIgDgLIgBgNIABgMQABgHACgFQACgFAEgFIAHgIQAEgEANgHQAJgCALAAQAGgBANAEQAJAEAGAGIAAgMIAZAAIAABsIgZAAIAAgOIgHAHIgIAGIgKACIgKABQgKABgJgEgAiLAXQgGADgEAEQgFAEgCAHQgDAGAAAGQAAAIADAGQACAGAFAFQAEAFAGACQAGADAHAAQAHAAAGgDQAGgCAEgFQAFgFACgGQADgGAAgIQAAgGgDgGQgCgGgFgFQgEgEgGgDQgGgDgHAAQgHAAgGADgAk5BrQgLgGgGgFIgHgIIgFgKIgDgLIgBgNIABgMIADgMQACgFADgFIAHgIQAFgEAMgHQAJgCALAAQAHgBANAEQAJAEAGAGIAAgMIAZAAIAABsIgZAAIAAgOIgHAHIgIAGIgKACQgFABgFAAQgKABgKgEgAkuAXQgGADgEAEQgFAEgDAHQgCAGAAAGQAAAIACAGQADAGAFAFQAEAFAGACQAGADAHAAQAGAAAHgDQAGgCAEgFQAEgFADgGQACgGAAgIQAAgGgCgGQgDgGgEgFQgEgEgGgDQgHgDgGAAQgHAAgGADgAD2BsQgIgCgHgCIgLgIIgLgKIAXgSIAGAHIAIAGIAHAEIAJABQAFAAAEgCQAEgBACgCQAGgFAAgIQAAgEgDgDQgCgDgEgDQgFgCgOgFIgOgEQgIgEgFgEQgFgEgDgGQgEgHAAgJQAAgIAEgHQADgGAGgGQAGgFAIgDQAIgDAKAAQAIAAAHACIAMADQAHAEALAKIgVAQQgEgHgGgCQgGgEgIAAIgIABIgGAEQgFAEAAAGQAAAEADADQABACAFACQAEADAPAFIAOAFQAHADAFAFQAGAEADAHQAEAHAAAKQAAAHgDAIQgDAHgGAGQgHAHgIADQgJADgLAAQgJAAgHgCgAm0BsQgGgBgHgCQgHgDgFgEIgKgJQgFgEgEgGIgFgLIgEgOQgCgGAAgHIACgPIAEgMIAGgNIAIgJIAKgIIAMgHQAGgDAHAAIAOgCQALAAAJACQAJADAJAFQAHAFAHAFQAGAHAEAHIgWANQgDgGgEgEQgEgFgFgDQgFgCgGgBQgGgBgHAAQgIAAgJADQgIADgGAGQgGAGgDAJQgDAHAAAKQAAAIADAJQADAJAGAFQAGAHAIADQAJAEAJAAQAIAAAHgDQAGgCAFgDIAJgJQADgGABgHIgqAAIAAgYIBGAAIAAALIgBAMIgEAOIgFALQgEAGgEAEIgKAIIgLAHIgNADQgHACgIAAIgPgCgAFSBsIAdguIgHABQgJAAgIgDQgIgEgGgGQgFgGgEgIQgDgJAAgKQAAgJADgIQAEgJAGgGQAHgHAIgDQAKgDAJAAQALAAAJADQAIAEAHAGQAGAHAEAIQAEAIAAAJQAAAJgDAKQgDAJgEAHIgkA4gAFkgEQgEACgEACQgDAEgCAEQgCAFAAAEQAAAFACAFQACAEADADQAEAEAEABQAEADAFAAQAFAAAEgDQAEgBAEgEIAEgIQACgEAAgFQAAgFgCgEIgEgIQgEgCgEgCQgEgCgFAAQgFAAgEACgAAUBsIgagkIgZAkIgfAAIApg3Igog1IAfAAIAYAiIAYgiIAeAAIgnA1IApA3gAjbBsIAAiIIAZAAIAACIgAG/BLIAAgYIgYAAIAAgVIAYAAIAAgXIAVAAIAAAXIAYAAIAAAVIgYAAIAAAYgAnchYIgEgDQgEgGAAgHIAAgFIATAAIAAAHQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQABACAEAAQAFAAABgFQABgEgBgCQgBgDgOgHQgOgIgCgIQgBgEABgFQADgPAVgBQAXABAAARIAAAFIgRAAIAAgFQAAgGgHAAQgFAAgBAFIABAEQAAADAOAHQAPAIABAJQABADgBAIQAAAEgDAEQgFAHgQAAQgLAAgGgEgAjAhbQgDgFAAgFIgBg2IASAAIAAA1QACAGAEgBQAGABABgGIAAg1IASAAIAAA2QgBAFgDAFQgGAGgPABQgOgBgGgGgAj9hZIgDgCQgFgFAAgJIAAgEIATAAIAAAHQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQACACAEAAQAFABABgFIAAgGQgBgDgPgHQgNgIgCgIIAAgJQADgPAVAAQAXAAAAARIAAAFIgRAAIAAgFQAAgFgGAAQgGgBgBAFIAAAEQABADAOAHQAPAJABAHQABAEgBAHQgBAFgCAEQgGAGgPABQgKgBgHgEgAgthZIgDgCQgEgFAAgGIAAgmQACgRAVAAQAXAAACARIAAAFIAAACIgRAAIAAgHQgCgFgGAAQgFAAgBAFIgBAiIABAEIABADIAFABQAEAAACgBQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAAgNIgIAAIAAgLIAZAAIAAAYQgBAGgEAFIgDACQgGAEgLAAQgJAAgHgEgAknhXIAAg9IAAAAIgMA9IgRAAIgMg9IAAA9IgRAAIABhEIAcAAIAIA1IABAAIAIg1IAcAAIACBEgAmChXIgJg+IAAAAIgJA+IgTAAIANhEIAeAAIANBEgAhfhYIgRg3IAAAAIABA3IgRAAIAAhDIAZAAIAQA2IAAAAIgBg2IASAAIAABDg");
	this.shape_1.setTransform(48.5,15.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_head_1, new cjs.Rectangle(-1.5,-7.6,106.4,53.9), null);


(lib.mc_handy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.instance = new lib.s9plus_100px();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.mc_handy, new cjs.Rectangle(0,0,100,212), null);


(lib.handyrechts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.instance = new lib.lg_44px();
	this.instance.parent = this;
	this.instance.setTransform(0,-2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.handyrechts, new cjs.Rectangle(0,-2,45,97), null);


(lib.handyfront = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.instance = new lib.huawei_P20_Pro_Charlotte_Black_FrontRight_BN_eciRGBv2();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.handyfront, new cjs.Rectangle(0,0,48,124), null);


(lib.blau = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.instance = new lib.samsung_galaxy_s9plus_g360_Coral_Blue_l30();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.blau, new cjs.Rectangle(0,0,37,100), null);


(lib._1und1_logo_80px_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib._1und1_logo_80px();
	this.instance.parent = this;
	this.instance.setTransform(32.7,32.5,0.938,0.938,0,0,0,34.9,34.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib._1und1_logo_80px_1, new cjs.Rectangle(-20.1,-20.3,125.1,120.5), null);


(lib.stoerer_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_37 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(37).call(this.frame_37).wait(1));

	// head
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#134094").s().p("AgJAxIAAhHIATAAIAABHgAgJgfIAAgRIATAAIAAARg");
	this.shape.setTransform(112.7,70.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#134094").s().p("AgLAiQgGgCgEgGQgIgKAAgQQAAgIACgGQACgHAEgFQAIgKANAAQAPAAAIAJQAHAKAAARIAAAGIgoAAQAAAGAEAFQAEAEAIAAQAKAAAKgDIAAAPIgLADQgGABgGAAQgHAAgHgDgAAMgGQAAgQgMAAQgKAAAAAQIAWAAIAAAAg");
	this.shape_1.setTransform(107.6,71.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#134094").s().p("AgFAwQgEgDgDgEIgEAHIgPAAIAAhhIAUAAIAAAgQAFgHAJAAQAHAAAFADQAFACAEAFQADAFACAGQACAGAAAJQAAAIgCAHQgBAHgFAFQgDAFgGADQgFACgGAAQgEABgEgCgAgHgHIgEADIAAAhQABADADABQACABADAAQAHAAADgFQADgGAAgLQAAgLgDgFQgDgFgHAAQgDAAgCACg");
	this.shape_2.setTransform(100.7,70.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#134094").s().p("AgXAhIAAgPQAMAEAIAAQADAAACgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAQAAgDgCgCQgCgDgHgDIgGgDIgFgDQgCgCgBgEQgCgDAAgFQAAgJAIgGQAHgGAJAAQAJAAAKADIAAAOQgKgDgGAAQgEAAgCACQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAIAFIAHAEIAFADQADACACAEIABAHQAAALgHAGQgEADgFACQgFABgFAAQgLAAgKgEg");
	this.shape_3.setTransform(90.7,71.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#134094").s().p("AgMAjQgGgDgEgFQgJgKAAgRQAAgQAJgKQAEgFAGgDQAFgCAHAAQAPAAAIAKQAJAKAAAQQAAARgJAKQgEAFgGADQgGACgHAAQgHAAgFgCgAgIgQIgCAHIAAAJQAAAMACAFQACADACABIAEACQADAAACgCQACgBACgDIACgHIAAgKIAAgJIgCgHQgDgGgGAAQgFAAgDAGg");
	this.shape_4.setTransform(84.3,71.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#134094").s().p("AgJAxIAAhhIATAAIAABhg");
	this.shape_5.setTransform(79,70.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#134094").s().p("AAJAkIAAguQAAgFgCgDQgCgCgEAAQgFABgEAFIAAAyIgUAAIAAhGIAQAAIACAHQAIgIAJgBQAFABAEABIAHAFQAFAGAAALIAAAwg");
	this.shape_6.setTransform(73.6,71.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#134094").s().p("AgLAiQgGgCgEgGQgIgKAAgQQAAgIACgGQACgHAEgFQAIgKANAAQAPAAAIAJQAHAKAAARIAAAGIgoAAQAAAGAEAFQAEAEAIAAQAKAAAKgDIAAAPIgLADQgGABgGAAQgHAAgHgDgAAMgGQAAgQgMAAQgKAAAAAQIAWAAIAAAAg");
	this.shape_7.setTransform(66.6,71.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#134094").s().p("AAAArQgDgCgCgDQgFgGAAgIIAAglIgMAAIAAgPIAMAAIAAgPIASAAIAAAPIAPAAIAAAPIgPAAIAAAiQAAAEACACQACACAEAAIAHAAIAAAOQgHABgIAAQgFAAgDgBg");
	this.shape_8.setTransform(60.7,71.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#134094").s().p("AgXAhIAAgPQAMAEAIAAQADAAACgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgDgCgCQgCgDgHgDIgGgDIgFgDQgCgCgBgEQgCgDAAgFQAAgJAIgGQAHgGAJAAQAJAAAKADIAAAOQgKgDgGAAQgEAAgCACQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABQAAABAAAAQABABAAAAQAAABAAAAQABABAAAAIAIAFIAHAEIAFADQADACACAEIABAHQAAALgHAGQgEADgFACQgFABgFAAQgLAAgKgEg");
	this.shape_9.setTransform(55.5,71.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#134094").s().p("AgMAjQgGgDgEgFQgJgKAAgRQAAgQAJgKQAEgFAGgDQAFgCAHAAQAPAAAIAKQAJAKAAAQQAAARgJAKQgEAFgGADQgGACgHAAQgHAAgFgCgAgIgQIgCAHIAAAJQAAAMACAFQACADACABIAEACQADAAACgCQACgBACgDIACgHIAAgKIAAgJIgCgHQgDgGgGAAQgFAAgDAGg");
	this.shape_10.setTransform(49.1,71.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#134094").s().p("AAKAxIgUgmIASghIAWAAIgWAhIAXAmgAgeAxIAAhhIAUAAIAAA7IAAAmgAgKALg");
	this.shape_11.setTransform(42.5,70.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#134094").s().p("AgRAxIAJgdIgYhEIAUAAIAMAsIAOgsIATAAIggBhg");
	this.shape_12.setTransform(110.2,57.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#134094").s().p("AgOAuQgFgCgEgFQgIgKAAgSQAAgIADgFQABgIAEgEQAHgKAOAAQAIAAAGAHIAAgfIATAAIAABgIgOAAIgEgGQgDADgEACQgEADgEAAQgGAAgGgEgAgKALQAAAYANAAIAFgCQADgBABgEIAAgfQgEgGgFAAQgNAAAAAUg");
	this.shape_13.setTransform(102.9,55.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#134094").s().p("AAJAkIAAguQAAgFgCgCQgCgCgEAAQgFgBgEAGIAAAyIgUAAIAAhGIAQAAIACAIQAIgKAJABQAFgBAEACIAHAFQAFAGABAKIAAAxg");
	this.shape_14.setTransform(95.8,56.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#134094").s().p("AgWAgQgEgDgBgEQgCgEAAgGQAAgIAGgHQAFgFAJgCIANgBIAHAAQAAgIgDgDQgDgDgIAAIgJABIgIACIgCACIAAgOQALgFALAAQAIAAAGABQAGACADADQAHAGAAAQIAAAsIgOAAIgEgJQgDAFgFACQgEADgGAAQgJAAgHgFgAgFAFQgFADAAAGQAAAFADACQADACAEAAQADAAAEgEQACgCABgDIABgGIAAgFIgEAAQgIAAgEACg");
	this.shape_15.setTransform(88.5,56.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#134094").s().p("AAMAtIAAglIgXAAIAAAlIgUAAIAAhZIAUAAIAAAkIAXAAIAAgkIAUAAIAABZg");
	this.shape_16.setTransform(81.1,55.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#134094").s().p("AgXAhIAAgPQAMAEAIAAQADAAACgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAQAAgDgCgCIgJgGIgGgDIgFgDQgCgCgBgEQgCgDAAgFQAAgJAIgGQAHgGAJAAQAJAAAKADIAAAOQgKgDgGAAQgEAAgCACQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABQAAAAAAABQAAABABAAQAAABAAAAQABABAAAAIAIAFIAHAEIAFADQADACACAEIABAHQAAALgHAGQgEADgFACQgFABgFAAQgLAAgKgEg");
	this.shape_17.setTransform(71,56.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#134094").s().p("AgLAiQgGgCgEgGQgIgKAAgQQAAgIACgGQACgHAEgFQAIgKANAAQAPAAAIAJQAHAKAAARIAAAGIgoAAQAAAGAEAFQAEAEAIAAQAKAAAKgDIAAAPIgLADQgGABgGAAQgHAAgHgDgAAMgGQAAgQgMAAQgKAAAAAQIAWAAIAAAAg");
	this.shape_18.setTransform(64.8,56.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#134094").s().p("AgWAeQgDgDgBgEQgBgEgBgGIAAgwIAUAAIAAAvQAAAFABACQACACAEAAIAGgBIAEgFIAAgyIATAAIAABGIgOAAIgEgHQgDAEgFACQgDADgGAAQgJAAgGgHg");
	this.shape_19.setTransform(57.8,56.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#134094").s().p("AgLAiQgGgCgEgGQgIgKAAgQQAAgIACgGQACgHAEgFQAIgKANAAQAPAAAIAJQAHAKAAARIAAAGIgoAAQAAAGAEAFQAEAEAIAAQAKAAAKgDIAAAPIgLADQgGABgGAAQgHAAgHgDgAAMgGQAAgQgMAAQgKAAAAAQIAWAAIAAAAg");
	this.shape_20.setTransform(50.7,56.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#134094").s().p("AALAtIgbg+IAAA+IgSAAIAAhZIAXAAIAcA+IAAg+IATAAIAABZg");
	this.shape_21.setTransform(43,55.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(38));

	// haken1
	this.instance = new lib.haken1();
	this.instance.parent = this;
	this.instance.setTransform(68.2,95);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({alpha:1},4).wait(22));

	// haken2
	this.instance_1 = new lib.haken2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(93.1,114.6,1,1,0,0,0,52.5,9.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(16).to({_off:false},0).to({alpha:1},4).wait(18));

	// haken3
	this.instance_2 = new lib.haken3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(65.3,134.2,1,1,0,0,0,24.7,9.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(20).to({_off:false},0).to({alpha:1},4).wait(14));

	// bg
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFED00").s().p("ApdIeIAAxeIS8htIAAVbg");
	this.shape_22.setTransform(91.1,94.8);

	this.timeline.addTween(cjs.Tween.get(this.shape_22).wait(38));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(30.4,26.2,121.3,137.3);


(lib.handylinks = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.instance = new lib.blau();
	this.instance.parent = this;
	this.instance.setTransform(20.6,55.5,1.11,1.11,0,0,0,18.5,50);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.handylinks, new cjs.Rectangle(0,0,41.1,111), null);


// stage content:
(lib._1810_DE_SSC_RET_M02_120_600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.body.style.margin = 0;
		
		stage.enableMouseOver();
		stage.update();
		var self = this;
		
		// loop = true, no-loop = false
		loop = false;
		
		this.instance.addEventListener("mouseover", fl_MouseOverHandler);
		this.instance.addEventListener("mouseout", fl_MouseOutHandler);
		
		function fl_MouseOverHandler(){
			document.querySelector('.tooltip.fade').classList.add('trick');
		}
		
		function fl_MouseOutHandler(){
			document.querySelector('.tooltip.fade').classList.remove('trick');
		}
	}
	this.frame_126 = function() {
		if(!this.alreadyExecuted){
		
			this.alreadyExecuted=true;
		
			this.loopNum=1;
		
		} else {
		
			this.loopNum++;
		
			if(this.loopNum==2){
		
				this.gotoAndStop(127);
		
			}
		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(126).call(this.frame_126).wait(97));

	// mouseover
	this.instance = new lib.mc_mouseover();
	this.instance.parent = this;
	this.instance.setTransform(101.9,354,1,1,0,0,0,50.6,107);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(117).to({_off:false},0).to({alpha:1},7).wait(92).to({alpha:0},6).wait(1));

	// 1und1_rahmen
	this.instance_1 = new lib._1und1_rahmen();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(223));

	// 1und1_logo
	this.instance_2 = new lib._1und1_logo_80px_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(57.4,535.5,1,1,0,0,0,34.9,34.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(223));

	// labels_1
	this.instance_3 = new lib.label_neu();
	this.instance_3.parent = this;
	this.instance_3.setTransform(78.5,24.3,1,1,0,0,0,45,17.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(64).to({_off:false},0).to({alpha:1},5).wait(43).to({alpha:0},6).to({_off:true},1).wait(104));

	// head_2
	this.instance_4 = new lib.head_24h();
	this.instance_4.parent = this;
	this.instance_4.setTransform(28.9,25.3,1,1,0,0,0,46.4,17.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(64).to({_off:false},0).to({alpha:1},5).wait(43).to({alpha:0},6).to({_off:true},1).wait(104));

	// stoerer_1
	this.instance_5 = new lib.stoerer_2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(120.7,156.6,0.055,1,0,0,0,151.4,94.8);
	this.instance_5.alpha = 0.301;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(64).to({_off:false},0).to({regX:151.7,scaleX:1,alpha:1},6).wait(42).to({regX:99,regY:55.2,x:68,y:117},0).to({alpha:0},6).to({_off:true},1).wait(104));

	// grafik_1
	this.instance_6 = new lib.grafik_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(58,49,1,1,0,0,0,58,49);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(64).to({_off:false},0).to({alpha:1},5).wait(43).to({alpha:0},6).to({_off:true},1).wait(104));

	// head_allnet_flat
	this.instance_7 = new lib.mc_head();
	this.instance_7.parent = this;
	this.instance_7.setTransform(49.5,36.4,1,1,0,0,0,41,19.5);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(117).to({_off:false},0).to({alpha:1},7).wait(92).to({alpha:0},6).wait(1));

	// flathaken
	this.instance_8 = new lib.mc_flathaken();
	this.instance_8.parent = this;
	this.instance_8.setTransform(62.7,198.8,1,1,0,0,0,50.6,107);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(117).to({_off:false},0).to({alpha:1},7).wait(92).to({alpha:0},6).wait(1));

	// handy front
	this.instance_9 = new lib.handyfront();
	this.instance_9.parent = this;
	this.instance_9.setTransform(83,360.3,1,1,0,0,0,22.5,46.5);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(117).to({_off:false},0).to({alpha:1},7).wait(92).to({alpha:0},6).wait(1));

	// handy links
	this.instance_10 = new lib.handylinks();
	this.instance_10.parent = this;
	this.instance_10.setTransform(58.5,369.8,1,1,0,0,0,22.5,46.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(117).to({_off:false},0).to({alpha:1},7).wait(92).to({alpha:0},6).wait(1));

	// handy rechts
	this.instance_11 = new lib.handyrechts();
	this.instance_11.parent = this;
	this.instance_11.setTransform(35.5,381.4,1,1,0,0,0,22.5,46.5);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(117).to({_off:false},0).to({alpha:1},7).wait(92).to({alpha:0},6).wait(1));

	// maske (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_145 = new cjs.Graphics().p("EgHyAluIAAjcIQwAAIAADcg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(145).to({graphics:mask_graphics_145,x:57.4,y:241.4}).wait(13).to({graphics:null,x:0,y:0}).wait(65));

	// glow
	this.maske = new lib.mc_glow();
	this.maske.parent = this;
	this.maske.setTransform(-183.1,438.2,3.546,0.635,0,35.8,0);
	this.maske._off = true;
	this.maske.cache(-5,-3,74,109);

	var maskedShapeInstanceList = [this.maske];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.maske).wait(145).to({_off:false},0).to({x:156.9},12).to({_off:true},1).wait(65));

	// maushand
	this.instance_12 = new lib.maushand_vector();
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.4,524.1,1,1,0,0,0,10.5,10.5);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(161).to({_off:false},0).to({x:112.5,y:488.5,alpha:1},15,cjs.Ease.get(-0.98)).wait(9).to({y:490.5},0).wait(2).to({y:488.5},0).wait(8).to({x:112,y:490.8},0).wait(2).to({x:112.5,y:488.5},0).wait(13).to({x:112,y:488.8},0).to({x:129.4,y:523.1,alpha:0},6,cjs.Ease.get(-1)).to({_off:true},1).wait(6));

	// infobutton
	this.instance_13 = new lib.mc_clickbtn();
	this.instance_13.parent = this;
	this.instance_13.setTransform(-23.6,464.4,1,1,0,0,0,82.5,26.4);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(117).to({_off:false},0).to({x:91.1},6).wait(62).to({y:466.9},0).wait(2).to({y:464.4},0).wait(8).to({y:466.9},0).wait(2).to({y:464.4},0).wait(19).to({alpha:0},6).wait(1));

	// sternchentext
	this.instance_14 = new lib.mc_sternchentext();
	this.instance_14.parent = this;
	this.instance_14.setTransform(85.5,590.5,1,1,0,0,0,83.5,5.1);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(111).to({_off:false},0).to({alpha:1},5).wait(98).to({alpha:0},6).to({_off:true},1).wait(2));

	// whitespot_03
	this.instance_15 = new lib.mc_whitespot_02();
	this.instance_15.parent = this;
	this.instance_15.setTransform(53.1,282.6,1,0.327,0,0,0,59.4,114.5);
	this.instance_15.alpha = 0;
	this.instance_15.shadow = new cjs.Shadow("rgba(0,153,255,1)",0,0,72);
	this.instance_15._off = true;
	this.instance_15.filters = [new cjs.BlurFilter(28, 28, 3)];
	this.instance_15.cache(-40,-293,212,698);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(64).to({_off:false},0).to({alpha:1},5).wait(42).to({alpha:0},5).wait(2).to({scaleY:0.23,x:62.8,y:379.5,alpha:1},0).wait(98).to({x:63.1,y:135},0).to({alpha:0},6).wait(1));

	// handy_logo
	this.instance_16 = new lib.mc_head_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(-53.3,101.6,1,1,0,0,0,48.1,11.8);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(3).to({_off:false},0).to({x:60.1},6).wait(48).to({alpha:0},6).to({_off:true},3).wait(157));

	// handy
	this.instance_17 = new lib.mc_handy();
	this.instance_17.parent = this;
	this.instance_17.setTransform(-56.7,257.4,1,1,0,0,0,45,104.5);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(3).to({_off:false},0).to({x:55.3},6).wait(48).to({alpha:0},6).to({_off:true},3).wait(157));

	// stoerer_head
	this.instance_18 = new lib.mc_stoerer();
	this.instance_18.parent = this;
	this.instance_18.setTransform(60,27.8,1,1,0,0,0,60,27.8);
	this.instance_18.alpha = 0;
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(3).to({_off:false},0).to({alpha:1},6).wait(48).to({alpha:0},6).to({_off:true},3).wait(157));

	// maske (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EgJXAu4MAAAhdvISvAAMAAABdvg");
	var mask_1_graphics_57 = new cjs.Graphics().p("EgJXAu4MAAAhdvISvAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:60,y:300}).wait(57).to({graphics:mask_1_graphics_57,x:60,y:300}).wait(166));

	// whitespot_02
	this.instance_19 = new lib.mc_whitespot_02();
	this.instance_19.parent = this;
	this.instance_19.setTransform(56,188.5,0.87,0.87,0,0,0,56,150.5);
	this.instance_19.alpha = 0;
	this.instance_19.shadow = new cjs.Shadow("rgba(45,192,255,1)",0,0,58);
	this.instance_19.filters = [new cjs.BlurFilter(52, 52, 2)];
	this.instance_19.cache(-40,-293,212,698);

	var maskedShapeInstanceList = [this.instance_19];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_19).to({alpha:1},6).wait(51).to({alpha:0},6).to({_off:true},3).wait(157));

	// 1und1_hintergrund
	this.instance_20 = new lib._1und1_hintergrund();
	this.instance_20.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(223));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(58.7,298.7,122.6,602.6);
// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/grafik_full_120px.png", id:"grafik_full_120px"},
		{src:"images/grafik_step1_120px.png", id:"grafik_step1_120px"},
		{src:"images/grafik_step2_120px.png", id:"grafik_step2_120px"},
		{src:"images/grafik_step3_120px.png", id:"grafik_step3_120px"},
		{src:"images/huawei_P20_Pro_Charlotte_Black_FrontRight_BN_eciRGBv2.png", id:"huawei_P20_Pro_Charlotte_Black_FrontRight_BN_eciRGBv2"},
		{src:"images/lg_44px.png", id:"lg_44px"},
		{src:"images/s9plus_100px.png", id:"s9plus_100px"},
		{src:"images/samsung_galaxy_s9plus_g360_Coral_Blue_l30.png", id:"samsung_galaxy_s9plus_g360_Coral_Blue_l30"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;